### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID: Chrome 58+ doesn't follow RFC

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/generator-office#271] opened 2017-12-18 23:17 UTC
Still, since Chrome is the default browser on most computers (`npm start` opens the browser), we should be Chrome compliant, Windows customers will see this error after running `npm start`. We need to update the generation script to include Subject Alternate Name (SAN), update the certs, and then republish.

http://www.expta.com/2017/06/fix-for-certificate-error-in-chrome.html

**Comment by kbrandl** [comment] 2018-01-04 18:49
Another issue apparently caused by the fact that `Subject Alternate Name (SAN)`  is missing from the cert that Yo Office generates:  https://github.com/OfficeDev/generator-office/issues/274.

**Comment by TCourtneyOwen** [comment] 2018-04-11 19:52
I have a pull request out now with the fix for this issue

**Comment by TCourtneyOwen** [comment] 2018-04-12 16:11
Fix for this issue pushed out to https://github.com/OfficeDev/generator-office

**Closed by TCourtneyOwen** 2018-04-12 16:11 UTC
