### ISSUE TITLE
Generator ignoring telemetry settings; erroring calling Application Insights

### ISSUE THREAD

**Issue by ChrisRomp** [OfficeDev/generator-office#541] opened 2020-06-23 20:53 UTC
I have run `npx office-addin-usage-data off` but when I run `yo office` it is still attempting to connect to Application Insights, which errors (blocked) and the package generator fails.

Repro steps:
1. Block application insights IPs
1. run `npx office-addin-usage-data off`
1. Run `yo office`
1. Select TaskPane React, TypeScript, Project

Here is the content of `%useprofile%\office-addin-usage-data.json`:
```javascript
{
  "usageDataInstances": {
    "office-addin-usage-data": {
      "usageDataLevel": "off"
    }
  }
}
```

Here is the output from the `yo office` console:
```powershell
C:\dev> yo office

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Office  │
    |--(o)--|    │   Add-in generator, by   │
   `---------´   │ @OfficeDev! Let's create │
    ( _´U`_ )    │    a project together!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Choose a project type: Office Add-in Task Pane project using React framework
? Choose a script type: TypeScript
? What do you want to name your add-in? ProjAddIn7
? Which Office client application would you like to support? Project

----------------------------------------------------------------------------------

      Creating ProjAddIn7 add-in for Project using TypeScript and React at C:\dev\ProjAddIn7

----------------------------------------------------------------------------------
ApplicationInsights:CorrelationIdManager [
  Error: connect ETIMEDOUT 40.84.189.107:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.84.189.107',
    port: 443
  }
]
C:\tools\node\node_modules\generator-office\node_modules\cls-hooked\context.js:177
      throw exception;
      ^

Error: connect ETIMEDOUT 192.30.255.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.255.112',
  port: 443,
  'error@context': { _ns_name: 'AI-CLS-Session', id: 246 }
}
C:\dev>
```

This is also possibly related to [this issue](https://github.com/OfficeDev/Office-Addin-Scripts/issues/290) at Office-Addin-Scripts.

The corporate firewall blocks telemetry of this nature. I've turned it off so would expect it to not be collecting data.

Thanks,
Chris

**Comment by ChrisRomp** [comment] 2020-06-23 21:02
Node version: `12.16.2`
Global packages:
```
+-- generator-office@1.7.1
+-- gulp@4.0.2
+-- npm@6.14.4
+-- webpack@4.43.0
+-- webpack-cli@3.3.11
`-- yo@3.1.1
```

**Comment by TCourtneyOwen** [comment] 2020-06-23 21:19
This is a duplicate of https://github.com/OfficeDev/Office-Addin-Scripts/issues/290. It's the same issue where Application Insights is unable to connect due firewall settings.  The fact that you have usage data set to "off" suggests a bug in the office-addin-usage-data package where the "off" setting is not being respected. I am investigating that now.  I am going to close this issue and continue tracking in https://github.com/OfficeDev/Office-Addin-Scripts/issues/290

**Closed by TCourtneyOwen** 2020-06-23 21:19 UTC

**Comment by ChrisRomp** [comment] 2020-06-23 21:22
No worries. Since the path to the bug was different I wanted to add some detail here, but I'll continue to track OfficeDev/Office-Addin-Scripts#290. Once that's resolved I can test this again and reopen if necessary.

**Comment by TCourtneyOwen** [comment] 2020-06-23 22:18
This is really mystifying - even after removing all usage data code locally in generator-office I am still hitting the error when I block port 443. It's almost as if there's another package dependency we are using that is calling AppInsights.  I took a look at the Yeoman-Generator code but don't see any conspicuous references to AppInights, but it's always possible that they have a dependency that's using it

**Comment by ChrisRomp** [comment] 2020-06-24 00:45
Ok, so I think what's _actually_ happening is that it's failing when trying to download the generator zip file [here](https://github.com/OfficeDev/generator-office/blob/master/src/app/helpers/helperMethods.ts#L38). But that error is caught and then emitted via AppInsight's Logger [here](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/CorrelationIdManager.ts#L83). 

So the issue is the zip package getting blocked, not AppInsights getting blocked, which makes sense.  It's just confusing because the error is emitted via the ApplicationInsights:CorrelationIdManager.  I wonder if the wrong Logger is getting called somehow? Or if the error message could be made a bit more clear somehow. The promise is getting rejected with the message `Unable to download project zip file for "${projectTemplateZipFile}".\n${err}`, but that doesn't show in the console.

My mistake. ¯\\\_(ツ)_/¯
