### ISSUE TITLE
Cannot select TypeScript when trying to create Angular Task Pane Outlook Add in

### ISSUE THREAD

**Issue by 0x80085** [OfficeDev/generator-office#769] opened 2023-04-13 18:28 UTC
# Expected behavior

I can select a angular typescript generator using the arrow keys

# Current behavior

I cannot select TypeScript after selecting Office Task Add In with Angular

## Steps to Reproduce

select a angular typescript generator using the arrow keys

I cannot select TypeScript after selecting Office Task Add In with Angular

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 11
* Node version: latest
* Office version: latest
* Tool version: latest

## Failure Logs

none, it simply doesn't let me select the typescript option even though it clearly is there on the screen

**Comment by millerds** [comment] 2023-04-13 19:01
This a duplicate of https://github.com/OfficeDev/generator-office/issues/757 . . . it's not specific to any one template type.

**Closed by millerds** 2023-04-13 19:01 UTC
Labels: duplicate

**Comment by 0x80085** [comment] 2023-04-13 19:02
Yes @millerds thanks for closing this! Was about to do the same after my last update of the comment in #757
