### ISSUE TITLE
Excel taskpane error in IE11

### ISSUE THREAD

**Issue by javierpr71** [OfficeDev/generator-office#477] opened 2019-08-13 08:34 UTC
I have open an issue in office-js project
https://github.com/OfficeDev/office-js/issues/662

I think this project is related with this bug too

**Comment by TCourtneyOwen** [comment] 2021-01-26 17:28
Dupe of https://github.com/OfficeDev/generator-office/issues/481

**Closed by TCourtneyOwen** 2021-01-26 17:28 UTC
