### ISSUE TITLE
SSO not working on IE or IE based desktop Outlook

### ISSUE THREAD

**Issue by skyhawk92** [OfficeDev/generator-office#559] opened 2020-09-28 10:55 UTC
I made a project for Outlook using "Taskpane add-in supporting single-sign-on", everything works fine in Edge and also desktop Outlook app where Windows 10 version is higher than 1903, which means, wherever desktop Outlook uses Edge to render add in.

When using IE browser or desktop Outlook that uses IE to render add in, it launches ok, but on clicking "Get My User Profile Information", nothing happens. I tried both typescript and javascript versions and used es5 as target, so IE should be able to render it, but it seems like it has trouble rendering js.

**To reproduce**  simply create "Taskpane add-in supporting single-sign-on" project and try to open it in IE browser.

**Comment by TCourtneyOwen** [comment] 2020-09-29 19:45
Thanks for reporting this issue. I am encountering the same behavior with the SSO template when loading in IE. I am investigating today and will get back to you.

-Courtney

**Comment by skyhawk92** [comment] 2020-09-29 21:16
Thank you for reply, would be interesting to see what is wrong.  I tried to set some logs as well, to see how far it gets in js files, and it looks like it doesn't even get to sso auth js file.

**Comment by TCourtneyOwen** [comment] 2020-09-30 19:48
I confirmed that this behavior is not unique to Outlook in IE webview. I was able to repro this behavior in Excel as well.  In my initial debugging, I am hitting this error:  "Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page."

**Comment by skyhawk92** [comment] 2020-09-30 21:35
> I confirmed that this behavior is not unique to Outlook in IE webview. I was able to repro this behavior in Excel as well. In my initial debugging, I am hitting this error: "Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page."

I don’t think office.onReady has anything to do with actual issue, since I saw it in many other projects as well and they worked.  Besides this project has onReady implemented and I don’t know what else could I try.

**Comment by skyhawk92** [comment] 2020-10-01 22:01
Issue lies in taskpane.js file within dist folder which gets generated, but I don't know to solve it.

**Comment by skyhawk92** [comment] 2020-10-06 12:48
@TCourtneyOwen I noticed office-addin-sso module gets translated to es6 as it has so defined in its package. That is the reason for failure. Any possible solutions ?

**Comment by skyhawk92** [comment] 2020-11-02 14:17
@TCourtneyOwen   Did you find any solutions to this ?

**Comment by TCourtneyOwen** [comment] 2020-11-02 17:10
I haven't been able to figure out a solution for this yet unfortunately. I just tried again this morning and the error that's causing it is the following:

Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it\'s loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

I see a similar issue with IE at https://stackoverflow.com/questions/58414479/office-js-onready-initialize-not-working-on-internet-explorer.  As stated in the post, querystring seems to be the problem.  I see in the SSO project that query string is an indirect dependency of webpack, and I am almost sure this issue is related to the way that the taskpane file is getting built

**Comment by millerds** [comment] 2021-06-15 22:26
Closing this for now.  If you still have problems or need help please reactivate.

**Closed** 2021-06-15 22:26 UTC
