### ISSUE TITLE
Unable to start the dev server

### ISSUE THREAD

**Issue by sarahboyce** [OfficeDev/generator-office#470] opened 2019-07-18 12:14 UTC
I was following the steps here:
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

Once I run npm start:
```
npm start

> office-addin-taskpane-js@0.0.1 start .....\My Office Add-in
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 05c2e1c9-3e1d-406e-9a91-e9ac64854143. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
Unable to start the dev server. Error: The dev server is not running on port 3000.
Sideloading the Office Add-in...
Debugging started.

```

![image](https://user-images.githubusercontent.com/42296566/61456430-49b70400-a966-11e9-8c60-9799ef74f5d9.png)

I am on Windows 10
Please can you help me run the add-in? Would really like to try this out :)

**Comment by TCourtneyOwen** [comment] 2019-07-18 15:02
@sarahboyce Did you see a prompt asking for approval to install certificates? You will need to say 'yes' to this certificate in order to start the dev-server.  Also, can you please run 'npm list generator-office -g' to see that you are using the latest version of generator-office (1.3.0).

**Comment by akrantz** [comment] 2019-07-18 15:18
@sarahboyce You should see a dialog like this, and click Yes.

![image](https://user-images.githubusercontent.com/741153/61469603-591d5980-a934-11e9-9dbe-b925fa334d66.png)

**Comment by sarahboyce** [comment] 2019-07-19 06:32
@akrantz thank you for getting back so quickly!
This doesn't appear for me - how do I make this pop up?

**Comment by sarahboyce** [comment] 2019-07-19 07:13
> @sarahboyce Did you see a prompt asking for approval to install certificates? You will need to say 'yes' to this certificate in order to start the dev-server. Also, can you please run 'npm list generator-office -g' to see that you are using the latest version of generator-office (1.3.0).

```
C:\Users\Sarah Boyce\AppData\Roaming\npm
`-- generator-office@1.3.0
```

**Comment by akrantz** [comment] 2019-07-19 13:52
@sarahboyce Run this command: `npx office-addin-dev-certs install`. 

If the certificates are already installed, you'll see a message:
```
You already have trusted access to https://localhost.
```

If the certificates are not installed, it will show a message:
```
The developer certificates have been generated in C:\Users\adamk\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
```
You should then see the dialog asking to install the certificate.

After saying yes, it should then show:
```
You now have trusted access to https://localhost.
```

Once the certificates are installed, you should be able to run the dev server without problems.

**Comment by sarahboyce** [comment] 2019-07-19 15:04
I ran it and it says...

```
The developer certificates have been generated in C:\Users\Sarah Boyce\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate. Import-Certificate : A positional parameter cannot be found that accepts argument
'Boyce\.office-addin-dev-certs\ca.crt'.
At line:1 char:1
+ Import-Certificate -CertStoreLocation cert:\CurrentUser\Root C:\Users ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-Certificate], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.CertificateServices.Commands.ImportCertificateComm
   and
```

**Comment by TCourtneyOwen** [comment] 2019-07-19 15:19
@akrantz I seem to recall that there is an issue with earlier versions of PowerShell not supporting Import-Certificate. Does that sound familiar?

**Comment by akrantz** [comment] 2019-07-19 15:31
No, the problem is that there are spaces in the username. See https://github.com/OfficeDev/Office-Addin-Scripts/issues/148. 

I just published the latest update a few minutes ago. 

@sarahboyce Please try `npx office-addin-dev-certs install` again. This will get the latest version and I think it should work this time.

**Comment by sarahboyce** [comment] 2019-07-19 20:47
@akrantz I gave it a go, but no joy:
```
C:\Users\Sarah Boyce\Documents\GitHub\ego-wch\My Office Add-in>npx office-addin-dev-certs install
The developer certificates have been generated in C:\Users\Sarah Boyce\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate. Import-Certificate : A positional parameter cannot be found that accepts argument
'Boyce\.office-addin-dev-certs\ca.crt'.
At line:1 char:1
+ Import-Certificate -CertStoreLocation cert:\CurrentUser\Root C:\Users ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-Certificate], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.CertificateServices.Commands.ImportCertificateComm
   and

```

**Comment by akrantz** [comment] 2019-07-19 21:07
@sarahboyce If you go to the directory "c:\users\Sarah Boyce\.office-addin-dev-certs", you could manually install the CA certificate. 

1. Double-click the ca.crt file.
2. Click the "Install Certificate..." button.
3. Choose "Current User" and click Next.
4. Choose "Place all certificates in the following store" and click Browse...
5. Select "Trusted Root Certification Authorities" and click OK.
6. Click Next and Finish.

Once the CA certificate is installed, `npm run dev-server` should be able to run successfully.

**Comment by Zoha** [comment] 2019-07-20 13:07
I also had this problem
This problem has been solved for me. I used Windows 7. After I changed my windows to 10 and after that, the certificates were successfully installed and the problem disappeared

**Comment by sarahboyce** [comment] 2019-07-20 15:29
@akrantz - that has sorted it! Thank you so much!

> @sarahboyce If you go to the directory "c:\users\Sarah Boyce.office-addin-dev-certs", you could manually install the CA certificate.
> 
> 1. Double-click the ca.crt file.
> 2. Click the "Install Certificate..." button.
> 3. Choose "Current User" and click Next.
> 4. Choose "Place all certificates in the following store" and click Browse...
> 5. Select "Trusted Root Certification Authorities" and click OK.
> 6. Click Next and Finish.
> 
> Once the CA certificate is installed, `npm run dev-server` should be able to run successfully.

**Comment by TCourtneyOwen** [comment] 2019-07-20 15:40
Great, glad you got up and running! Closing this issue. 

-Courtney

**Closed by TCourtneyOwen** 2019-07-20 15:40 UTC

**Comment by mortezamsp** [comment] 2019-08-18 09:16
i had the same problem, but there is a point: your project folder name must not include any space characters. i renamed project folders and problem fixed.
if it didn't  help  you, run "npm run dev-server" to see more about error.
