### ISSUE TITLE
Error: Unable to parse C:\Users\Jeremy\src\.bowerrc: Unexpected token M

### ISSUE THREAD

**Issue by jthake** [OfficeDev/generator-office#51] opened 2015-10-06 22:21 UTC
Got this error on a fresh windows 10 environment with node, git installed after running

npm install -g yo generator-office bower

I used yo office and for folder location "\My First" and it threw an error. Iwanted it to create a sub folder and add there but it broke. Doing it with "/MyFirst" with no space and the bower bit works fine. Looks like its something on how the bower command is run.

It appears it doesn't adhere to the folder structure as not everything gets put in the subfolder "MyFirst".

Got this error 

C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\util\rc.js:56
        throw error;
        ^

Error: Unable to parse C:\Users\Jeremy\src\.bowerrc: Unexpected token M
    at parse (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\util\rc.js:49:21)
    at C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\util\rc.js:76:20
    at Array.forEach (native)
    at json (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\util\rc.js:74:14)
    at rc (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\util\rc.js:31:9)
    at Config.load (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\Config.js:14:20)
    at Function.Config.read (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\Config.js:49:19)
    at readCachedConfig (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\lib\config.js:21:51)
    at defaultConfig (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\lib\config.js:11:24)
    at Object.<anonymous> (C:\Users\Jeremy\AppData\Roaming\npm\node_modules\bower\lib\index.js:40:32)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! my-first@0.1.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-first@0.1.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the my-first package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls my-first
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jeremy\src\npm-debug.log

C:\Users\Jeremy\src>

**Comment by andrewconnell** [comment] 2015-10-13 09:25
I've tried this using node v4.1.2 on both OSX & Windows 8.1 with the app having a space in the folder name & not having a space... can't repo.

The problem looks to be rooted in that it didn't do the pathing correct to `.bowerrc` rather it missed the `\` after `src` and thus, looked for a `src.bowerrc` file... which makes sense why bower blew up. Can you verify the `.bowerrc` file was created in the root of the project folder correctly? If so, then it's a bower issue, not an issue with our generator. Not passing the buck, but trying to isolate where the issue is.

With that being said, I have seen some stuff that people have had issues with NPM & yeoman on Node v4.x... for now, can't repo as I don't have a Windows 10 machine to test on.

**Comment by andrewconnell** [comment] 2015-10-16 09:40
Closing due to lack of followup. Feel free to reopen if you have further info.

**Closed by andrewconnell** 2015-10-16 09:40 UTC
Labels: question
