### ISSUE TITLE
Can't add/generate a new component in angular outlook app.

### ISSUE THREAD

**Issue by ahsan566** [OfficeDev/generator-office#409] opened 2019-01-29 22:39 UTC
I generated an angular application for outlook using yo office, added the add-in to outlook desktop and it worked fine but when I try to generate a new component in the app, it throws me this error,
 
![image](https://user-images.githubusercontent.com/22573942/51945037-4a52f100-243f-11e9-8b12-24eac00022aa.png)

I am definitely in the app's directory.

When I added the component files manually, and added the new component name inside app.module's declarations array, the plugin displays nothing but blank screen.

Also there is no angular-cli,json or angular.json file in the project.

Angular CLI: 7.2.1
Node: 10.14.1
OS: win32 x64
Angular: 5.2.11
typescript: 3.2.4

**Comment by ksurvell** [comment] 2019-02-05 13:49
I've had the same exact problems, except I was creating a Word add-in:

- None of the Angular CLI commands work due to the missing angular.json file.
- Adding components manually causes the add-in to display nothing but a blank screen.

**Comment by Alcid3** [comment] 2019-04-03 10:58
Same here for angular.json..

I am able to add manually components and displaying them as expected.
Your blank screen is probably caused by the fact you don't have accepted the certs. used by the local web server => Open the url of the add-in in your browser and accept the security exception for the local destination.

**Comment by ragavanrajan** [comment] 2019-06-26 22:16
Does it mean angular.json will be missed out in future releases ? Its really hard to add manually everytime when you want to generate component / services. Any update will be appreciated

**Comment by ragavanrajan** [comment] 2019-06-27 01:22
@Alcid3 Can you please be elaborate. I have added the components and the .ts file. When I add the component in app.module.ts it breaks immediately. I followed your instructions and in the browser no certs are showing. Anything which I am missing

**Comment by igor-ribeiiro** [comment] 2022-06-13 17:47
This seems to be a duplicate of: https://github.com/OfficeDev/generator-office/issues/365
The office currently is not having an integration with @angular/cli

**Closed by igor-ribeiiro** 2022-06-13 17:47 UTC
