### ISSUE TITLE
readme has ugly table at top

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/generator-office#472] opened 2019-07-19 18:44 UTC
![image](https://user-images.githubusercontent.com/741153/61557956-88a69180-aa1a-11e9-9ffa-3bca83ef9a89.png)

@kbrandl Would you mind fixing this?

**Comment by kbrandl** [comment] 2019-07-19 18:50
@akrantz unfortunately this table is here "by design" and needs to remain (as-is). It's adding metadata for this repo so that the repo can be surfaced to users in search results within the Office Dev Portal (e.g., as shown [here](https://developer.microsoft.com/en-us/office/gallery/?filterBy=Add-ins)).

**Comment by kbrandl** [comment] 2019-07-19 18:53
Actually, here's another link that better shows **generator-office** in the search results when filtering by "Add-ins" and "Tools":  https://developer.microsoft.com/en-us/office/gallery/?filterBy=Add-ins,Tools

**Comment by akrantz** [comment] 2019-07-19 19:13
Can this be moved to the end?

**Comment by kbrandl** [comment] 2019-07-19 19:18
@akrantz I think it needs to exist at the top of the README, but I'm not certain as I wasn't involved in implementing the process that uses it.

@nokafor do I recall correctly that you were involved in adding this metadata to the top of the README in several GitHub repos (so that they'll be searchable via the Office Dev Portal)?  If so, can you please answer @akrantz's question re positioning?  i.e., does the metadata have to exist as the first thing in the README, or can it be moved to the end?

**Comment by kbrandl** [comment] 2019-07-22 17:44
@akrantz do you want to close this issue, per our discussion last week? To recap -- this table at the top of the README makes it so that the **OfficeDev/generator-office** repository will show up in search results on the Office Dev portal (when the user filters by "Tools" and "Add-ins", for example). AFAIK, it must appear at the top of the README, and while you could technically remove the table altogether, doing so would mean that this repo would no longer appear in search results within the Office Dev portal.

**Comment by akrantz** [comment] 2019-07-22 17:47
I'd like to keep it open until we really have a resolution. I don't see much value in having these and would prefer to just remove this from the readme so it appears nicer, and then drive the issue of needing a better way for a project to appear in the Office Dev portal search results.

**Comment by kbrandl** [comment] 2019-07-22 18:01
Okay, that's fair. In that case, I'm re-assigning this issue to @nokafor (Sylvia Okafor); she's also requested that you send her an email to express your feedback about this table appearing at the top of READMEs throughout repos in **OfficeDev**, so that she can share the feedback with the appropriate folks.

**Comment by millerds** [comment] 2022-05-24 17:47
Is this still a problem?

**Closed** 2023-03-21 23:40 UTC
