### ISSUE TITLE
Outlook plugin - Angular with TypeScript - object doesn't support error

### ISSUE THREAD

**Issue by arora-kushal** [OfficeDev/generator-office#337] opened 2018-07-09 10:18 UTC
Hi Team,

I have just created new outlook plugin through following commands:

yo office
> Angular
> TypeScript
> HelloWorld
> Outlook

And I just updated the "SupportUrl" in manifest.xml file.

After that I sideloaded this in outlook but I am getting following error. Please suggest

Unhandled exception at line 80437, column 25 in https://localhost:3000/app.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'from'

**Comment by TCourtneyOwen** [comment] 2018-07-10 17:21
Thanks for reaching out. I will have a look into this and get back to you.

-Courtney

**Comment by TCourtneyOwen** [comment] 2018-07-11 17:12
I just tried creating an Angular Outlook add-in and didn't have any problems sideloading the add-in the Outlook **desktop** application. I add the following as the SuppportUrl:

 <SupportUrl DefaultValue="https://localhost:3000/resource.html" />

Does the add-in sideload successfully if you comment out or completely remove the SupportUrl element from the manifest? Also, can you please clarify if you were trying to sideload the add-in in Outlook Online or the desktop application?

Thanks,

Courtney

**Comment by arora-kushal** [comment] 2018-07-11 17:54
Yes, the add-in sideloaded successfully if I provide dummy supporturl or comment out.

I am trying to sideload it in Outlook on Windows 10.

Should i share my code as attachment here ?

**Comment by TCourtneyOwen** [comment] 2018-07-11 17:55
Sure, if you are willing to share your code that'd be great.

Thanks,

Courtney

**Comment by arora-kushal** [comment] 2018-07-11 18:05
Uploading files except node modules folder.

[HelloWorld.zip](https://github.com/OfficeDev/generator-office/files/2185675/HelloWorld.zip)

**Comment by TCourtneyOwen** [comment] 2018-07-11 22:23
I am not hitting any conspicuous errors when trying to sideload add-in in my instance of Outlook, even I provide a legitimate SuppportUrl.  Can you please let me know what build of Outlook you are using by checking File->Office Account->About Outlook?

**Comment by arora-kushal** [comment] 2018-07-12 05:38
Version 1806 (Build 10228.20080)

Microsoft Outlook 2016 MSO (16.0.10228.20080) 32-bit

**Comment by TCourtneyOwen** [comment] 2018-07-12 15:52
Judging by your version of Office, this looks like an Microsoft internal build.  Do you happen to work at Microsoft? If so, can you perhaps update your Office instance to a more recent build? I am currently running 16.0.10325.20003 64 Bit Outlook, and as I mentioned am not encountering the error you see

**Comment by arora-kushal** [comment] 2018-07-15 07:36
updated my build to latest one : 10228.20104

https://docs.microsoft.com/en-us/officeupdates/monthly-channel-2018

It seems like an issue with 32 bit Outlook issue.

**Comment by TCourtneyOwen** [comment] 2018-07-16 16:01
If you use the 64-bit version does the add-in now work?  I will check and see about any issues with 32-bit Outlook.  

Thanks,

Courtney

**Comment by arora-kushal** [comment] 2018-07-17 05:02
Sorry, I would not able to test it on 64 bit as its not available for us. Could you please let us know the results on 32 bit ?

Thanks,
Kushal Arora

**Comment by TCourtneyOwen** [comment] 2018-07-17 16:04
I will try out 32 bit this morning and let you know how it goes.  You may be correct that this is a 32 bit problem only.

-Courtney

**Comment by arora-kushal** [comment] 2018-07-18 06:12
Yes, sure. Please let us know.

Also, just to clarify, you will get this error if you have unselected "disable script debugging (IE)" and "disable script debugging (other) in Internet Options in IE. 
Otherwise, if they are checked, you won't see any error in Outlook, its just that your add-in will flicker/won't display anything.

**Comment by TCourtneyOwen** [comment] 2018-07-18 16:20
OK, I too am now seeing this error when changing the IE settings as suggested. I found an article that seems to be related and am going to investigate a fix.  The article I am referring to is https://stackoverflow.com/questions/35576694/ie-11-angularjs-error-object-doesnt-support-property-or-method-from

I will keep you posted.

Thanks,

Courtney

**Comment by TCourtneyOwen** [comment] 2018-07-23 17:40
Hi,

Just wanted to send an update and let you know I am still looking into this. I was able to get past "the 'Object doesn't support property or method 'from' by updating the angular dependecies packages in package.json as follows:

    "@angular/common": "6.0.9",
    "@angular/compiler": "6.0.9",
    "@angular/core": "6.0.9",
    "@angular/platform-browser": "6.0.9",
    "@angular/platform-browser-dynamic": "6.0.9",

However, I am now hittng this error:   **Object doesn't support property or method 'fill'**

The crux of the problem is that IE11, which is the default browser for Office add-ins, has incompatabilty issues with the javascript generated for Angular projects.

I am going to continue lookign at this and see if I can somehow get past the **Object doesn't support property or method 'fill'** error

**Comment by TCourtneyOwen** [comment] 2018-07-23 20:06
FYI, if you are looking to get up and running right away, you can create an Angular Outlook **Javascript** project and that'll work.  Just follow the same process you did when generating the Typescript version, but select "Javascript" instead of Typescript when promoted in Yo Office.

I am continuing to try and figure out a workaround for the Typescript Angular project

-Courtney

**Comment by TCourtneyOwen** [comment] 2018-07-23 20:59
OK, I think I have the fix for this. Extract the attached zip file to the root folder of your add-in project directory. This will replace your project's package.json and webpack.config.js with the attached versions, which will use polyfill to address to work around the issues that were causing javascript errors.  After replacing your versions of the attached files (as well as copying over .babelrc to your project root folder), run **npm install** at the root of your project and then **npm run build**

Please let me know if this fixes the problem. I will work to get the fix published out ASAP.

Thanks,

Courtney
[OutlookAngularTypescri[tFix.zip](https://github.com/OfficeDev/generator-office/files/2221005/OutlookAngularTypescri.tFix.zip)

**Comment by TCourtneyOwen** [comment] 2018-07-24 16:03
The fix for this issue has been checked into the generator-office repo at https://github.com/OfficeDev/generator-office.  I will publish a new version of Yo Office this morning.  If you want to pick up the fix immediately, please follow the "**Development** steps on https://github.com/OfficeDev/generator-office.

Thanks,

Courtney

**Closed by TCourtneyOwen** 2018-07-24 16:03 UTC

**Comment by TCourtneyOwen** [comment] 2018-07-24 17:47
I just published out a new version of generator office to NPM with the fix for this issue.  The updated version is v. 1.1.15.

-Courtney

**Comment by arora-kushal** [comment] 2018-07-25 05:57
Its working fine now. Thanks for your help on this.
